### ISSUE TITLE
does not appear properly on mobile 

### ISSUE THREAD

**Issue by USMP-lancer** [MEEPofFaith/testing-utilities#1]
probably dont matter, still an issue

**Comment by MEEPofFaith** [comment]
![more info needed](https://user-images.githubusercontent.com/54301439/110025463-41027580-7ce4-11eb-98a3-bda8f4068242.png)

**Comment by USMP-lancer** [comment]
yes

**Comment by USMP-lancer** [comment]
this is how it appears to me lol
![image](https://user-images.githubusercontent.com/42185819/110026255-0a355b00-7cf6-11eb-9773-30237baf2f25.png)

**Comment by USMP-lancer** [comment]
imma try it with no mods on besides it

**Comment by USMP-lancer** [comment]
still gon
a

**Comment by USMP-lancer** [comment]
i can use the console if needed

**Comment by MEEPofFaith** [comment]
is it possible for you to give me the last_log?

**Comment by USMP-lancer** [comment]
sure, just tell me how

**Comment by MEEPofFaith** [comment]
Well on PC the wall of text that shows up when opening the console is the last log, does the same happen on mobile?

**Comment by USMP-lancer** [comment]
nothing much shows up, no errors, perhaps its fine, but is off screen

**Comment by Alexey-41** [comment]
Hello. I wanted to ask... when approximately will the error with the image of the buttons be fixed? just I want to try out new features

P.S sorry for the mistakes, i'm russian

**Comment by MEEPofFaith** [comment]
I have no idea why it doesn't show

**Comment by Alexey-41** [comment]
ok, I will wait and hope

**Comment by USMP-lancer** [comment]
something something its prob just rendering off screen

**Comment by USMP-lancer** [comment]
@MEEPofFaith just so you know you can force run desktop in android mode through console, can be useful to debug

**Comment by USMP-lancer** [comment]
Vars.testMobile=true
although it prob has to be run at startup

**Comment by USMP-lancer** [comment]
ok i reused dev-mode to run at startup, try it if you want to continue to work on this, and if it dont work, idek
[test mobile1.zip](https://github.com/MEEPofFaith/testing-utilities/files/6095661/test.mobile1.zip)
