### ISSUE TITLE
Schema bug

### ISSUE THREAD

**Issue by Alexey-41** [MEEPofFaith/testing-utilities#2]
After the scheme is copied or pasted, the game crashes ... Can I write about bugs here?

**Comment by MEEPofFaith** [comment]
let me guess.
mobile?

**Comment by Alexey-41** [comment]
Yes of course)

**Comment by Alexey-41** [comment]
https://user-images.githubusercontent.com/76983778/110257123-dfe6e480-7ff8-11eb-898a-f7b85ec6aca4.mp4

Video to confirm that I'm not lying

**Comment by MEEPofFaith** [comment]
could you get me the crash report?

**Comment by Alexey-41** [comment]
yes, but how ... I'm new to github and the game

**Comment by MEEPofFaith** [comment]
`Settings` -> `Game Data` -> `Export Crash Logs`

**Comment by Alexey-41** [comment]
Okey, thanks

**Comment by Alexey-41** [comment]
But... It is empty

**Comment by Alexey-41** [comment]
But... It is empty

**Comment by Alexey-41** [comment]
0 bytes

**Comment by Alexey-41** [comment]
And another question, can it depend on the phone?

**Comment by abrasmag3** [comment]
Same problem, notes:
Android, moto g power
no crash log

**Comment by Alexey-41** [comment]
I here rummaged in the game files ... and found a folder crashes and there I found a crash due to copying

**Comment by Alexey-41** [comment]
[crash_1615182563306.txt](https://github.com/MEEPofFaith/testing-utilities/files/6099198/crash_1615182563306.txt)

**Comment by Alexey-41** [comment]
Here ... If you still need it, and forgive the crooked translation, this is written by the program Gboard

**Comment by Alexey-41** [comment]
and I can also send an error in inserting a schema
