### ISSUE TITLE
Cloning massive bug

### ISSUE THREAD

**Issue by Wadelmer** [MEEPofFaith/testing-utilities#9]
In campaign if you try to clone yourself, the core literally explodes and everything dissapears so you will need to reconquer that sector, I accidentaly cloned myself 2 times and lost everything I've done.

**Comment by Goobrr** [comment]
It's not a bug, it's a feature™

**Comment by MEEPofFaith** [comment]
# ***My anti-cheat strikes again!***

**Comment by Wadelmer** [comment]
So I'm forced to disable the mod in campaign, no? Lol

**Comment by MEEPofFaith** [comment]
I made the buttons not clickable when in campaign for a reason.
If you removed the disabled things, you could probably remove the anti-cheat as well
